### ISSUE TITLE
나누기 기능 제작

### ISSUE THREAD

**Issue by isaiahIM** [MTVS-BE3-TEAM4/calculator#3]
# 요구사항
- 두 수를 나눌 수 있다.
- 두 수를 나누는 메소드를 제작한다.
- 인자값으로 나눌 두 수를 입력받아 나눈 결과값을 반환한다.

# TASK
- [x] 두 수를 인자값으로 받는다
- [x] 두 수를 나눈다
- [x] 나눈 값을 반환한다
- [x] 만약 0으로 나누는 경우 예외를 발생시킨다.
